### ISSUE TITLE
Not working on TeamCity 8.1.5

### ISSUE THREAD

**Issue by algiecas** [enlivenhq/teamcity-slack#1]
The tab "Slack Notifier" is not shown in Notification Rules. How can I further troubleshoot this?

**Comment by aivus** [comment]
I have 8.1.5 (build 30240). All works fine.

**Comment by irobinson** [comment]
@aivus thanks for letting us know. Glad to hear!

**Comment by shanzzam** [comment]
I have a fresh install of Team City 9.0.4 (build 32407) and I am not seeing the tab "Slack Notifier" in Notification Rules as the original poster.  It is in my plugin list and I've restarted my service several times.  Would you like a new issue open for 9.0.4?  I do see that another user has this going in 9.0 however.

**Comment by irobinson** [comment]
@shanzzam awesome thanks for following up on that, glad to hear it is working. I'm wondering if the other version compatibility issues have a similar cause. We've yet to do much further testing with different versions unfortunately.
