### ISSUE TITLE
Enable building with Gradle

### ISSUE THREAD

**Issue by eljobe** [enlivenhq/teamcity-slack#30]
I'd like to be able to build this plugin with the [gradle-teamcity-plugin](https://github.com/rodm/gradle-teamcity-plugin) in addition to with maven.

The gradle plugin has some nice features like not needing to maintain a separate teamcity-plugin.xml file, being able to launch and control a test instance of various teamcity versions directly from the gradle command line, and including the version number in the generated zip file.

This can be added in a way that doesn't interfere with the maven build, and if you like it better, the project can be migrated to only using the gradle build by just removing the extraneous configuration files like the pom.xml files and the teamcity-plugin.xml file.

Pull request on it's way.

**Comment by aclarklestein** [comment]
Wow, yeah that sounds great. I know we've always found maven to be a bit of a pain in the process of making this plugin, so if this simplifies things I'm all for it.
