### ISSUE TITLE
Teamcity 10.0.2 and Rocket.Chat

### ISSUE THREAD

**Issue by Franziskus1988** [enlivenhq/teamcity-slack#39]
I tried to use this plugin with Teamcity 10.0.2 and Rocket.Chat but I got absolutely no notification. Normally Rocket.Chat should be 100% compatible with slack integrations, so I suggest that this plugin doesn't work on such a new Teamcity version. 

Can anybody deny or confirm this suggestion?

**Comment by dev1x** [comment]
This integration works on Teamcity 10.0.2.
Have you configured according to the README.md and tested the Slack incoming webhook?
