### ISSUE TITLE
Update Installation instruction

### ISSUE THREAD

**Issue by b3zn0gim** [enlivenhq/teamcity-slack#5]
README says to download zip and follow instructions, but there is no zip in repo =)

**Comment by irobinson** [comment]
@b3zn0gim there is a zip in the repo - https://github.com/enlivenhq/teamcity-slack/blob/master/target/teamcity-slack-integration.zip

However, at this time I don't believe it reflects the latest enhancement, which was including better formatting options in the message to slack.
