### ISSUE TITLE
Can't get it working (TeamCity 9)

### ISSUE THREAD

**Issue by evil-shrike** [enlivenhq/teamcity-slack#8]
Hi.
I installed the plugin in my TC 9.0.4. I logged in as an admin (but it's LDAP/AD-account) and setup Slack Notifier. But there're no any messages from Notifier in Slack. The instance url is correct as I checked it by posting a message manually (via curl). 
Is there any logs somewhere to understand what is going on?

**Comment by cy6erskunk** [comment]
You might need to change log4j config (to catch messages from `com.enlivenhq.*`) 

You could do following steps:

1. edit `config/_logging/debug-notifications.xml` adding section
  ```xml
  <category name="com.enlivenhq" additivity="false">
    <priority value="DEBUG"/>
    <appender-ref ref="NOTIFICATIONS.LOG"/>
</category>
```

2. switch `Active logging preset` to `debug-notifications` (at `Administration -> Diagnostics` page, `Troubleshooting` Tab) 
3. Go check `teamcity-notifications.log` file

**Comment by di97mni** [comment]
I done the [steps above](https://github.com/enlivenhq/teamcity-slack/issues/8#issuecomment-127979851) but no messages is sent.
I also tested successfully to post to the Slack endpoint.
Nothing is written in the log file regarding this plugin. I have restarted and tried several times.

The only notifiers written in the log file is these:
```
[2015-08-13 17:11:29,696]   INFO - n.email.EMailNotificatorConfig - Loading configuration file: C:\ProgramData\JetBrains\TeamCity\config\_notifications\email\email-config.xml 
[2015-08-13 17:11:31,292]   INFO - jabber.JabberNotificatorConfig - Loading configuration file: C:\ProgramData\JetBrains\TeamCity\config\_notifications\jabber\jabber-config.xml 
```
TeamCity Professional 9.0 (build 32060)

Any ideas?

**Comment by irobinson** [comment]
@di97mni have you tried re-installing the plugin? There's a chance it may have failed silently, I believe I've heard of that happening and that re-installing it using the same steps has worked for some folks.
